### ISSUE TITLE
Can't save new VM on clean install

### ISSUE THREAD

**Issue by seba76** [seba-0/qemu4dsm#1]
Traceback (most recent call last):
  File "./api.cgi", line 4, in <module>
    from app import app
  File "/volume1/@appstore/qemu4dsm/ui/app/__init__.py", line 1, in <module>
    from flask import Flask
  File "/volume1/@appstore/qemu4dsm/ui/flask/__init__.py", line 17, in <module>
    from werkzeug.exceptions import abort
ImportError: No module named werkzeug.exceptions

**Comment by seba76** [comment]
added dependency into INFO file
